[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"

cameraCore = "1.5.2"
cameraView = "1.5.2"
cameraLifecycle = "1.5.2"
cameraVideo = "1.5.2"

#cameraCore = "1.3.0"
#cameraView = "1.3.0"
#cameraLifecycle = "1.3.0"
#cameraVideo = "1.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraVideo" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

